### ISSUE TITLE
Error: No variants remaining after --exclude.

### ISSUE THREAD

**Issue by masen1991** [immunogenomics/HLA-TAPAS#9] opened 2021-08-23 06:27 UTC
Hi @WansonChoi ,

 i try to use hg38 version KGP samples to build a reference panel,but i get like this :
[5] Encoding SNP positions.
Error: No variants remaining after --exclude.
 and then it all go wrong after this step.

Do u have any idea? i try to use SNP2HLA-MakeReference,the old version ,but snps in hg18 ,it go well.

**Comment by WansonChoi** [comment] 2021-09-06 08:59
@masen0407 

Hi, Thank you for your report.

I'm sorry, but it's hard for me to figure out the exact cause only with this information.

The error message implicates it failed around step 5 of MakeReference_v2, but previous steps could have failed, too. (and this caused the failure of PLINK implementation).

Can you share the PLINK log file that failed last and the HLA-TAPAS main log file?

**Comment by masen0407** [comment] 2021-09-08 02:39
@WansonChoi 
Sorry for the missing info.
i use     --save-intermediates and upload all log file and the main log 
the command i use like this :
 python -m MakeReference \
    --variants DIR/KGP_EUR/hg38 \
    --chped DIR/KGP_EUR.chped \
    --hg 38 \
    --out DIR/test_hla_tapas/KGP_EUR/hg38 \
    --dict-AA MakeReference/data/hg38/HLA_DICTIONARY_AA.hg38.imgt3320 \
    --dict-SNPS MakeReference/data/hg38/HLA_DICTIONARY_SNPS.hg38.imgt3320 \
    --phasing \
    --mem 100g \
    --nthreads 72 \
    --save-intermediates
[main_log.txt](https://github.com/immunogenomics/HLA-TAPAS/files/7125336/main_log.txt)
[hg38.SNPS.TMP.log](https://github.com/immunogenomics/HLA-TAPAS/files/7125337/hg38.SNPS.TMP.log)
[hg38.SNPS.FOUNDERS.log](https://github.com/immunogenomics/HLA-TAPAS/files/7125338/hg38.SNPS.FOUNDERS.log)
[hg38.SNPS.CODED.log](https://github.com/immunogenomics/HLA-TAPAS/files/7125339/hg38.SNPS.CODED.log)
[hg38.MERGED.FOUNDERS.log](https://github.com/immunogenomics/HLA-TAPAS/files/7125340/hg38.MERGED.FOUNDERS.log)
[hg38.MERGED.FOUNDERS.FRQ.log](https://github.com/immunogenomics/HLA-TAPAS/files/7125341/hg38.MERGED.FOUNDERS.FRQ.log)
[hg38.log](https://github.com/immunogenomics/HLA-TAPAS/files/7125342/hg38.log)
[hg38.HLA.log](https://github.com/immunogenomics/HLA-TAPAS/files/7125343/hg38.HLA.log)
[hg38.HLA.FOUNDERS.log](https://github.com/immunogenomics/HLA-TAPAS/files/7125344/hg38.HLA.FOUNDERS.log)
[hg38.FRQ.log](https://github.com/immunogenomics/HLA-TAPAS/files/7125345/hg38.FRQ.log)
[hg38.FOUNDERS.QC.log](https://github.com/immunogenomics/HLA-TAPAS/files/7125346/hg38.FOUNDERS.QC.log)
[hg38.FOUNDERS.log](https://github.com/immunogenomics/HLA-TAPAS/files/7125348/hg38.FOUNDERS.log)
[hg38.FOUNDERS.hardy.log](https://github.com/immunogenomics/HLA-TAPAS/files/7125349/hg38.FOUNDERS.hardy.log)
[hg38.FOUNDERS.freq.log](https://github.com/immunogenomics/HLA-TAPAS/files/7125351/hg38.FOUNDERS.freq.log)
[hg38.AA.TMP.log](https://github.com/immunogenomics/HLA-TAPAS/files/7125352/hg38.AA.TMP.log)
[hg38.AA.FOUNDERS.log](https://github.com/immunogenomics/HLA-TAPAS/files/7125353/hg38.AA.FOUNDERS.log)
[hg38.AA.CODED.log](https://github.com/immunogenomics/HLA-TAPAS/files/7125354/hg38.AA.CODED.log)

IF u need  i can share you the *bed file to make reference and the cped file.

**Comment by WansonChoi** [comment] 2021-09-09 00:25
@masen0407 

If you can, please share the genotype data(*.{bed,bim,fam}) and chped file, too. Then, I can investigate the cause more closely.

**Comment by masen0407** [comment] 2021-09-09 01:14
> @masen0407
> 
> If you can, please share the genotype data(*.{bed,bim,fam}) and chped file, too. Then, I can investigate the cause more closely.
i put all files in a zip.
[KGP_EUR.zip](https://github.com/immunogenomics/HLA-TAPAS/files/7132619/KGP_EUR.zip)

**Comment by masen0407** [comment] 2021-10-05 10:21
@WansonChoi 
Do u have any results?

**Closed** 2024-01-28 01:06 UTC
